### ISSUE TITLE
format an SD card

### ISSUE THREAD

**Issue by akshayrf12345** [cloudmesh/cloudmesh-pi-burn#9]
We would need a command which could format an SD card

- [ ] review generl/cmburn.py and see what needs to be implemented
- [ ] even in pi/* the burn command has many more options, many of which have not even been attempted to be reimplemented

Add here the things we need, we want to file at one point separate issues, for now, we just collect here. We will reevaluate all features which are required as previous activities were not completed

- [x] review the manual page and see what needs to be there and implemented
- [x] hostname on sd card
- [x] static ip on sd card
- [x] key on sd card
- [x] switch on sshd
- [x] disable password login
- [x] allow WIFI to be configured on sd crad 
- [ ] evaluate other features from general/cmburn

**Comment by laszewsk** [comment]
This issue was not completed and motivates a complete redo of the pi burn activity. The previous work failed to leverage methods that were perfectly working in general/cmburn.py A review of previous activities in cmburn.py was not conducted. 

Major flaws were not being worked on or tested such as having the default password deactivated. The previous version of cm pi burn I would not even consider as pre-alpha due to the bugs and the highly incomplete implementation of that. 

We will start collecting all the issues we see. At this time we should consider the project as 0% done. The result of this is based on a re-review of this work being done over the Christmas break.

**Comment by rickotten** [comment]
Kernel panic-not syncing: VFS: unable to mount root fs on unknown-block(179,2)
https://raspberrypi.stackexchange.com/questions/40854/kernel-panic-not-syncing-vfs-unable-to-mount-root-fs-on-unknown-block179-6

This error occasionally happens when booting up pi3 for first time. Fixed by using cm-pi-burn again. Not sure why this is hapenning.

**Comment by laszewsk** [comment]
have you made sure the card you place in the burner is formatted properly, we assume that is the case ...

**Comment by laszewsk** [comment]
Should this be added to or FAQ.

**Comment by rickotten** [comment]
Added to FAQ/Hints. Closing.
